### ISSUE TITLE
built working sd image.

### ISSUE THREAD

**Issue by gavan1** [unframework/licheepi-nano-buildroot#12]
@unframework It would be a great help for the community if we had a working image for those that can't replicate the full dev environment.

**Comment by unframework** [comment]
Hmm, this sounds theoretically doable but the problem is that I don't know what utilities should be packaged in the image. The raw OS by itself is not super useful. This is actually why I wanted to set up this repo - to have a starter base configuration for someone to extend it and make per-project customized OS builds. But if there is a standard use case to build for, I could look into making an image?

By the way, there may be some pre-built image links from the manufacturer's site (http://nano.lichee.pro/get_started/first_eye.html), although I haven't checked that recently.

Thanks for the suggestion! And if you are running into specific problems with setting up dev build, let me know!
