### ISSUE TITLE
post-script.sh Permission denied

### ISSUE THREAD

**Issue by timfisc** [unframework/licheepi-nano-buildroot#2]
Hi I've run the script like you explained. after 1 hour he said make error: post-script.sh Permission denied. How can I fix it? Thanks in advance.

**Comment by timfisc** [comment]
Also can you attach a finished sdcard.img eventually? Thanks in advance and keep the good work up!!!

**Comment by unframework** [comment]
Thanks for the kind words!

Hmm, `post-script.sh` sounds unfamiliar, did you mean `post-image.sh`? For latter, you might want to run `chmod 755 board/licheepi_nano/post-image.sh`

Re: posting a binary image, there are actually some prebuilt ones out there, even on GitHub (sorry I don't have a link handy). I'm not planning to host a built image in this repo because this is meant more as a starting point for even more OS customization, etc...
